### ISSUE TITLE
Token\Token: isValid() method returns "false" even if the access_token is not yet expired

### ISSUE THREAD

**Issue by amarchiaro** [fazland/mailup-rest-client#5]
In the _isValid()_ function, the operator **<** should be changed with **>** in this way:

    public function isValid(): bool
    {
        return $this->validUntil > time() + 30;
    }

otherwise it will return **false** even if the _validUntil_ value is a date in the future.

**Comment by massimilianobraglia** [comment]
Hello @amarchiaro, thanks for reporting this.

Good point! I'll make a fix as soon as possible.

**Comment by massimilianobraglia** [comment]
Hi there again. 
I have this in 2a3b2bf35ddc4d288f29ed071f3a886e986f03ef.

Thank you again for your report.
